name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: 'recursive'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
          
      - name: Add Packages Nuget
        run: dotnet nuget add source https://nuget.pkg.github.com/Cappta/index.json -n GitHub -u Cappta -p ${{ secrets.PAT }} --store-password-in-clear-text

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack Release
        #if: github.ref == 'refs/heads/main'
        run: dotnet pack --output $(Build.ArtifactStagingDirectory) --include-symbols --include-source /p:Configuration=Release;RepositoryUrl=https://github.com/${{ github.repository }};PackageVersion=$(Build.BuildNumber) --verbosity Detailed
